/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.watergis.gui.panels;

import Sirius.navigator.DefaultNavigatorExceptionHandler;

import com.vividsolutions.jts.geom.Geometry;
import com.vividsolutions.jts.geom.LineString;

import org.apache.log4j.Logger;

import org.openide.util.NbBundle;

import java.awt.EventQueue;

import java.text.DecimalFormat;

import java.util.Collection;

import de.cismet.cismap.commons.Crs;
import de.cismet.cismap.commons.features.Feature;
import de.cismet.cismap.commons.features.FeatureCollectionEvent;
import de.cismet.cismap.commons.features.FeatureCollectionListener;
import de.cismet.cismap.commons.gui.piccolo.eventlistener.MessenGeometryListener;
import de.cismet.cismap.commons.interaction.CismapBroker;
import de.cismet.cismap.commons.interaction.StatusListener;
import de.cismet.cismap.commons.interaction.events.StatusEvent;

import de.cismet.watergis.broker.AppBroker;

/**
 * DOCUMENT ME!
 *
 * @author   Gilles Baatz
 * @version  $Revision$, $Date$
 */
public class StatusBar extends javax.swing.JPanel implements StatusListener, FeatureCollectionListener {

    //~ Static fields/initializers ---------------------------------------------

    private static final Logger LOG = Logger.getLogger(StatusBar.class);
    private static int K_DIVISOR = 1000;
    private static int K_SQUARE_DIVISOR = K_DIVISOR * K_DIVISOR;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private de.cismet.tools.gui.exceptionnotification.ExceptionNotificationStatusPanel exceptionNotificationStatusPanel;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblCoordinates;
    private javax.swing.JLabel lblMeasuring;
    private javax.swing.JPanel pnlCoordinates;
    private javax.swing.JPanel pnlMeasuring;
    // End of variables declaration//GEN-END:variables

    //~ Constructors -----------------------------------------------------------

    /**
     * Creates a new StatusBar object.
     */
    public StatusBar() {
        initComponents();
        lblCoordinates.setText(""); // NOI18N
        try {
            AppBroker.getInstance().getMappingComponent().getFeatureCollection().addFeatureCollectionListener(this);
        } catch (NullPointerException e) {
        }
        DefaultNavigatorExceptionHandler.getInstance().addListener(exceptionNotificationStatusPanel);
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0),
                new java.awt.Dimension(0, 0),
                new java.awt.Dimension(32767, 0));
        jPanel2 = new javax.swing.JPanel();
        pnlMeasuring = new javax.swing.JPanel();
        lblMeasuring = new javax.swing.JLabel();
        pnlCoordinates = new javax.swing.JPanel();
        lblCoordinates = new javax.swing.JLabel();
        exceptionNotificationStatusPanel =
            new de.cismet.tools.gui.exceptionnotification.ExceptionNotificationStatusPanel();
        jPanel1 = new javax.swing.JPanel();

        setMaximumSize(new java.awt.Dimension(32769, 20));
        setMinimumSize(new java.awt.Dimension(200, 20));
        setPreferredSize(new java.awt.Dimension(500, 20));
        addMouseListener(new java.awt.event.MouseAdapter() {

                @Override
                public void mouseClicked(final java.awt.event.MouseEvent evt) {
                    formMouseClicked(evt);
                }
            });
        setLayout(new java.awt.GridBagLayout());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.weightx = 1.0;
        add(filler1, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        add(jPanel2, gridBagConstraints);

        pnlMeasuring.setLayout(new java.awt.BorderLayout());
        pnlMeasuring.add(lblMeasuring, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 10);
        add(pnlMeasuring, gridBagConstraints);

        pnlCoordinates.setLayout(new java.awt.BorderLayout());

        org.openide.awt.Mnemonics.setLocalizedText(
            lblCoordinates,
            org.openide.util.NbBundle.getMessage(StatusBar.class, "StatusBar.lblCoordinates.text")); // NOI18N
        pnlCoordinates.add(lblCoordinates, java.awt.BorderLayout.CENTER);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(0, 2, 0, 2);
        add(pnlCoordinates, gridBagConstraints);
        add(exceptionNotificationStatusPanel, new java.awt.GridBagConstraints());
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        add(jPanel1, gridBagConstraints);
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  evt  DOCUMENT ME!
     */
    private void formMouseClicked(final java.awt.event.MouseEvent evt) { //GEN-FIRST:event_formMouseClicked
        if (evt.getClickCount() > 1) {
            if (!CismapBroker.getInstance().getMappingComponent().isInternalLayerWidgetVisible()) {
                CismapBroker.getInstance().getMappingComponent().showInternalLayerWidget(true, 300);
            } else {
                CismapBroker.getInstance().getMappingComponent().showInternalLayerWidget(false, 150);
            }
        }
    }                                                                    //GEN-LAST:event_formMouseClicked

    /**
     * DOCUMENT ME!
     *
     * @param  e  DOCUMENT ME!
     */
    @Override
    public void statusValueChanged(final StatusEvent e) {
        final Runnable modifyControls = new Runnable() {

                @Override
                public void run() {
                    if (e.getName().equals(StatusEvent.COORDINATE_STRING)) {
                        lblCoordinates.setText(e.getValue().toString());
                    } else if (e.getName().equals(StatusEvent.MEASUREMENT_INFOS)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.MAPPING_MODE)) {
                        // do nothing                                                          // NOI18N
                    } else if (e.getName().equals(StatusEvent.OBJECT_INFOS)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.SCALE)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.CRS)) {
                        lblCoordinates.setToolTipText(((Crs)e.getValue()).getShortname());
                    } else if (e.getName().equals(StatusEvent.RETRIEVAL_STARTED)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.RETRIEVAL_COMPLETED)
                                || e.getName().equals(StatusEvent.RETRIEVAL_ABORTED)
                                || e.getName().equals(StatusEvent.RETRIEVAL_REMOVED)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.RETRIEVAL_ERROR)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.MAP_EXTEND_FIXED)) {
                        // do nothing
                    } else if (e.getName().equals(StatusEvent.MAP_SCALE_FIXED)) {
                        // do nothing
                    }
                }
            };

        if (e.getName().equals(StatusEvent.MAPPING_MODE)) {
            // do nothing
        } else if (e.getName().equals(StatusEvent.RETRIEVAL_STARTED)) {
            // do nothing
        } else if (e.getName().equals(StatusEvent.RETRIEVAL_COMPLETED)) {
            // do nothing
        } else if (e.getName().equals(StatusEvent.RETRIEVAL_ABORTED)) {
            // do nothing
        } else if (e.getName().equals(StatusEvent.RETRIEVAL_ERROR)) {
            // do nothing
        } else if (e.getName().equals(StatusEvent.RETRIEVAL_REMOVED)) {
            // do nothing
        } else if (e.getName().equals(StatusEvent.RETRIEVAL_RESET)) {
            // do nothing
        }

        if (EventQueue.isDispatchThread()) {
            modifyControls.run();
        } else {
            EventQueue.invokeLater(modifyControls);
        }
    }

    /**
     * DOCUMENT ME!
     *
     * @param   d  DOCUMENT ME!
     *
     * @return  DOCUMENT ME!
     */
    private double roundTo2Decimals(final double d) {
        return (((int)(d * 100)) / 100.0);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  f  DOCUMENT ME!
     */
    private void showMeasuring(final Feature f) {
        final Geometry geom = f.getGeometry();
        double area = geom.getArea();
        double length = geom.getLength();

        if (geom.getArea() == 0) {
            final int segments = geom.getNumGeometries() * (geom.getNumPoints() - 1);

            if (length < 10000) {
                lblMeasuring.setText(NbBundle.getMessage(
                        StatusBar.class,
                        "StatusBar.lblMeasuring.text.length.m",
                        segments,
                        roundTo2Decimals(length)));
            } else {
                area /= K_SQUARE_DIVISOR;
                length /= K_DIVISOR;
                lblMeasuring.setText(NbBundle.getMessage(
                        StatusBar.class,
                        "StatusBar.lblMeasuring.text.length.km",
                        segments,
                        roundTo2Decimals(length)));
            }
        } else {
            if (length < 10000) {
                lblMeasuring.setText(NbBundle.getMessage(
                        StatusBar.class,
                        "StatusBar.lblMeasuring.text.m",
                        roundTo2Decimals(length),
                        roundTo2Decimals(area)));
            } else {
                area /= K_SQUARE_DIVISOR;
                length /= K_DIVISOR;
                lblMeasuring.setText(NbBundle.getMessage(
                        StatusBar.class,
                        "StatusBar.lblMeasuring.text.km",
                        roundTo2Decimals(length),
                        roundTo2Decimals(area)));
            }
        }
    }

    @Override
    public void featuresAdded(final FeatureCollectionEvent fce) {
        final Collection<Feature> features = fce.getEventFeatures();

        if (AppBroker.getInstance().getMappingComponent().getInteractionMode().equals(AppBroker.MEASURE_MODE)) {
            if ((features != null) && (features.size() == 1)) {
                final Feature f = features.toArray(new Feature[1])[0];
                showMeasuring(f);
            }
        }
    }

    @Override
    public void allFeaturesRemoved(final FeatureCollectionEvent fce) {
    }

    @Override
    public void featuresRemoved(final FeatureCollectionEvent fce) {
        lblMeasuring.setText("");
    }

    @Override
    public void featuresChanged(final FeatureCollectionEvent fce) {
        final Collection<Feature> features = fce.getEventFeatures();

        if (AppBroker.getInstance().getMappingComponent().getInteractionMode().equals(AppBroker.MEASURE_MODE)) {
            if ((features != null) && (features.size() == 1)) {
                final Feature f = features.toArray(new Feature[1])[0];
                showMeasuring(f);
            }
        }
    }

    @Override
    public void featureSelectionChanged(final FeatureCollectionEvent fce) {
    }

    @Override
    public void featureReconsiderationRequested(final FeatureCollectionEvent fce) {
    }

    @Override
    public void featureCollectionChanged() {
    }
}
