/***************************************************
*
* cismet GmbH, Saarbruecken, Germany
*
*              ... and it just works.
*
****************************************************/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.watergis.gui.panels;

import java.awt.Dimension;

import javax.swing.JLabel;

/**
 * DOCUMENT ME!
 *
 * @author   therter
 * @version  $Revision$, $Date$
 */
public class StatusPanel extends javax.swing.JPanel {

    //~ Enums ------------------------------------------------------------------

    /**
     * DOCUMENT ME!
     *
     * @version  $Revision$, $Date$
     */
    public static enum IconColor {

        //~ Enum constants -----------------------------------------------------

        GREY, GREEN, RED
    }

    //~ Instance fields --------------------------------------------------------

    private JLabel[] statusLabels;

    //~ Constructors -----------------------------------------------------------

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form StatusPanel.
     */
    public StatusPanel() {
        initComponents();
    }

    //~ Methods ----------------------------------------------------------------

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        setLayout(new java.awt.GridBagLayout());
    } // </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param  count  DOCUMENT ME!
     */
    public void setCount(final int count) {
        statusLabels = new JLabel[count];

        for (int i = 0; i < count; ++i) {
            statusLabels[i] = new JLabel();
            statusLabels[i].setIcon(new javax.swing.ImageIcon(
                    getClass().getResource("/de/cismet/watergis/res/icons16/status-offline.png")));
            add(statusLabels[i], new java.awt.GridBagConstraints());
        }

        setSize(count * 16, (int)getSize().getHeight());
        setMinimumSize(new Dimension(count * 16, (int)getSize().getHeight()));
        setMaximumSize(new Dimension(count * 16, (int)getSize().getHeight()));
        setPreferredSize(new Dimension(count * 16, (int)getSize().getHeight()));
    }

    /**
     * DOCUMENT ME!
     *
     * @param  index    DOCUMENT ME!
     * @param  tooltip  DOCUMENT ME!
     */
    public void setTooltip(final int index, final String tooltip) {
        statusLabels[index].setToolTipText(tooltip);
    }

    /**
     * DOCUMENT ME!
     *
     * @param  index  DOCUMENT ME!
     * @param  color  DOCUMENT ME!
     */
    public void setStatusIcon(final int index, final IconColor color) {
        switch (color) {
            case GREY: {
                statusLabels[index].setIcon(new javax.swing.ImageIcon(
                        getClass().getResource("/de/cismet/watergis/res/icons16/status-offline.png")));
                break;
            }
            case GREEN: {
                statusLabels[index].setIcon(new javax.swing.ImageIcon(
                        getClass().getResource("/de/cismet/watergis/res/icons16/status.png")));
                break;
            }
            case RED: {
                statusLabels[index].setIcon(new javax.swing.ImageIcon(
                        getClass().getResource("/de/cismet/watergis/res/icons16/status-busy.png")));
                break;
            }
        }
    }
}
