/**
 * *************************************************
 *
 * cismet GmbH, Saarbruecken, Germany
 * 
* ... and it just works.
 * 
***************************************************
 */
/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package de.cismet.watergis.gui;

import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;

import net.infonode.docking.RootWindow;
import net.infonode.docking.util.DockingUtil;
import net.infonode.docking.util.StringViewMap;

import org.apache.commons.cli.CommandLine;
import org.apache.commons.cli.Options;
import org.apache.commons.cli.PosixParser;
import org.apache.log4j.Logger;
import org.apache.log4j.PropertyConfigurator;

import org.jdom.Element;

import java.awt.Dimension;
import java.awt.Point;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

import de.cismet.tools.configuration.Configurable;
import de.cismet.tools.configuration.ConfigurationManager;

import de.cismet.tools.gui.startup.StaticStartupTools;

import de.cismet.watergis.broker.AppBroker;

import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.event.WindowEvent;
import java.awt.event.WindowListener;

/**
 * DOCUMENT ME!
 *
 * @author thorsten
 * @version $Revision$, $Date$
 */
public class WatergisApp extends javax.swing.JFrame implements Configurable, WindowListener {

    //~ Static fields/initializers ---------------------------------------------
    private static final Logger LOG = Logger.getLogger(WatergisApp.class);
    private static JFrame SPLASH;
    private static final ConfigurationManager configManager = new ConfigurationManager();
    private static final String FILENAME_WATERGIS_CONFIGURATION = "defaultWatergisProperties.xml";
    private static final String FILENAME_LOCAL_WATERGIS_CONFIGURATION = "watergisProperties.xml";
    private static final String CLASSPATH_WATERGIS_CONFIGURATION = "/de/cismet/watergis/configuration/";
    private static final String DIRECTORYPATH_HOME = System.getProperty("user.home");
    private static final String DIRECTORYEXTENSION = System.getProperty("directory.extension");
    private static final String FILESEPARATOR = System.getProperty("file.separator");
    private static final String DIRECTORYNAME_WATERGISHOME = ".watergis"
            + ((DIRECTORYEXTENSION != null) ? DIRECTORYEXTENSION : "");
    private static final String DIRECTORYPATH_WATERGIS = DIRECTORYPATH_HOME + FILESEPARATOR
            + DIRECTORYNAME_WATERGISHOME;
    private static final String FILEPATH_DEFAULT_LAYOUT = DIRECTORYPATH_WATERGIS + FILESEPARATOR + "watergis.layout";
    private static final String FILEPATH_PLUGIN_LAYOUT = DIRECTORYPATH_WATERGIS + FILESEPARATOR
            + "pluginWatergis.layout";
    private static final String FILEPATH_DEFAULT_APP_DATA = DIRECTORYPATH_WATERGIS + FILESEPARATOR + "watergis.data";
    private static final String FILEPATH_SCREEN = DIRECTORYPATH_WATERGIS + FILESEPARATOR + "watergis.screen";

    static {
        configManager.setDefaultFileName(FILENAME_WATERGIS_CONFIGURATION);
        configManager.setFileName(FILENAME_LOCAL_WATERGIS_CONFIGURATION);
        configManager.setClassPathFolder(CLASSPATH_WATERGIS_CONFIGURATION);
        configManager.setFolder(DIRECTORYNAME_WATERGISHOME);
    }
    //~ Instance fields --------------------------------------------------------
    private RootWindow rootWindow;
    private StringViewMap viewMap = new StringViewMap();
    // Configurable
    private Dimension windowSize = null;
    private Point windowLocation = null;

    //~ Constructors -----------------------------------------------------------
    /**
     * Creates new form WatergisApp.
     */
    public WatergisApp() {
        this.addWindowListener(this);

        configManager.addConfigurable(this);
        configManager.configure(this);
        initComponents();
        initDocking();
        setWindowSize();
    }

    //~ Methods ----------------------------------------------------------------
    /**
     * DOCUMENT ME!
     */
    private void initDocking() {
        rootWindow = DockingUtil.createRootWindow(viewMap, true);
        AppBroker.getInstance().setRootWindow(rootWindow);
    }

    /**
     * DOCUMENT ME!
     */
    private static void initLog4J() {
        try {
            PropertyConfigurator.configure(WatergisApp.class.getResource(
                    "/de/cismet/watergis/configuration/log4j.properties"));
            LOG.info("Log4J System erfolgreich konfiguriert");
        } catch (Exception ex) {
            System.err.println("Fehler bei Log4J Initialisierung");
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menFile = new javax.swing.JMenu();
        mniOpenProject = new javax.swing.JMenuItem();
        mniSaveProject = new javax.swing.JMenuItem();
        mniWindow = new javax.swing.JMenuItem();
        mniPrint = new javax.swing.JMenuItem();
        mniExportMap = new javax.swing.JMenuItem();
        mniCreateGeoLink = new javax.swing.JMenuItem();
        mniFileOptions = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mniClose = new javax.swing.JMenuItem();
        menBookmark = new javax.swing.JMenu();
        mniCreateBookmark = new javax.swing.JMenuItem();
        mniManageBookmarks = new javax.swing.JMenuItem();
        menSelection = new javax.swing.JMenu();
        mniSelectForm = new javax.swing.JMenuItem();
        mniSelectAttribute = new javax.swing.JMenuItem();
        mniSelectLocation = new javax.swing.JMenuItem();
        mniZoomSelectedObjects = new javax.swing.JMenuItem();
        mniRemoveSelection = new javax.swing.JMenuItem();
        mniSelectionOptions = new javax.swing.JMenuItem();
        menHelp = new javax.swing.JMenu();
        mniHelp = new javax.swing.JMenuItem();
        mniInfo = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle(org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.title")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(menFile, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.menFile.text")); // NOI18N

        mniOpenProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-folder-open.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniOpenProject, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniOpenProject.text")); // NOI18N
        menFile.add(mniOpenProject);

        mniSaveProject.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-save-floppy.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniSaveProject, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniSaveProject.text")); // NOI18N
        menFile.add(mniSaveProject);

        mniWindow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-newwindow.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniWindow, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniWindow.text")); // NOI18N
        menFile.add(mniWindow);

        mniPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-print.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniPrint, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniPrint.text")); // NOI18N
        menFile.add(mniPrint);

        mniExportMap.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-export.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniExportMap, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniExportMap.text")); // NOI18N
        menFile.add(mniExportMap);

        mniCreateGeoLink.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-link.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniCreateGeoLink, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniCreateGeoLink.text")); // NOI18N
        menFile.add(mniCreateGeoLink);

        mniFileOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-settingsandroid.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniFileOptions, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniFileOptions.text")); // NOI18N
        menFile.add(mniFileOptions);
        menFile.add(jSeparator1);

        jMenuItem8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-explorerwindow.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jMenuItem8, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.jMenuItem8.text")); // NOI18N
        menFile.add(jMenuItem8);

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-explorerwindow.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jMenuItem11, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.jMenuItem11.text")); // NOI18N
        menFile.add(jMenuItem11);
        menFile.add(jSeparator2);

        jMenuItem9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-explorerwindow.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jMenuItem9, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.jMenuItem9.text")); // NOI18N
        menFile.add(jMenuItem9);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-explorerwindow.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(jMenuItem12, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.jMenuItem12.text")); // NOI18N
        menFile.add(jMenuItem12);
        menFile.add(jSeparator3);

        mniClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-programclose.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniClose, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniClose.text")); // NOI18N
        menFile.add(mniClose);

        jMenuBar1.add(menFile);

        org.openide.awt.Mnemonics.setLocalizedText(menBookmark, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.menBookmark.text")); // NOI18N

        mniCreateBookmark.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-circleadd.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniCreateBookmark, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniCreateBookmark.text")); // NOI18N
        menBookmark.add(mniCreateBookmark);

        mniManageBookmarks.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-bookmark.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniManageBookmarks, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniManageBookmarks.text")); // NOI18N
        menBookmark.add(mniManageBookmarks);

        jMenuBar1.add(menBookmark);

        org.openide.awt.Mnemonics.setLocalizedText(menSelection, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.menSelection.text")); // NOI18N

        mniSelectForm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-selectionadd.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniSelectForm, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniSelectForm.text")); // NOI18N
        menSelection.add(mniSelectForm);

        mniSelectAttribute.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-selectionadd.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniSelectAttribute, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniSelectAttribute.text")); // NOI18N
        menSelection.add(mniSelectAttribute);

        mniSelectLocation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-selectionadd.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniSelectLocation, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniSelectLocation.text")); // NOI18N
        menSelection.add(mniSelectLocation);

        mniZoomSelectedObjects.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-resize.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniZoomSelectedObjects, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniZoomSelectedObjects.text")); // NOI18N
        menSelection.add(mniZoomSelectedObjects);

        mniRemoveSelection.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-selectionremove.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniRemoveSelection, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniRemoveSelection.text")); // NOI18N
        menSelection.add(mniRemoveSelection);

        mniSelectionOptions.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-settingsandroid.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniSelectionOptions, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniSelectionOptions.text")); // NOI18N
        menSelection.add(mniSelectionOptions);

        jMenuBar1.add(menSelection);

        org.openide.awt.Mnemonics.setLocalizedText(menHelp, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.menHelp.text")); // NOI18N

        mniHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-question-sign.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniHelp, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniHelp.text")); // NOI18N
        menHelp.add(mniHelp);

        mniInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/de/cismet/watergis/res/icons/icon-info-sign.png"))); // NOI18N
        org.openide.awt.Mnemonics.setLocalizedText(mniInfo, org.openide.util.NbBundle.getMessage(WatergisApp.class, "WatergisApp.mniInfo.text")); // NOI18N
        menHelp.add(mniInfo);

        jMenuBar1.add(menHelp);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * DOCUMENT ME!
     *
     * @param args DOCUMENT ME!
     */
    public static void main(final String[] args) {
        Thread.setDefaultUncaughtExceptionHandler(new Thread.UncaughtExceptionHandler() {
            @Override
            public void uncaughtException(final Thread t, final Throwable e) {
                LOG.error("Uncaught Exception in " + t, e);
            }
        });
        initLog4J();
        try {
            final Options options = new Options();
            options.addOption("u", true, "CallserverUrl");
            options.addOption("c", true, "ConnectionClass");
            options.addOption("d", true, "Domain");
            final PosixParser parser = new PosixParser();
            final CommandLine cmd = parser.parse(options, args);
            if (cmd.hasOption("u")) {
                AppBroker.getInstance().setCallserverUrl(cmd.getOptionValue("u"));
            } else {
                LOG.warn("Kein Callserverhost spezifiziert, bitte mit -u setzen.");
                System.exit(1);
            }
            if (cmd.hasOption("c")) {
                AppBroker.getInstance().setConnectionClass(cmd.getOptionValue("c"));
            } else {
                LOG.warn("Keine ConnectionClass spezifiziert, bitte mit -c setzen.");
                System.exit(1);
            }
            if (cmd.hasOption("d")) {
                AppBroker.getInstance().setDomain(cmd.getOptionValue("d"));
            } else {
                LOG.error("Keine Domain spezifiziert, bitte mit -d setzen.");
                System.exit(1);
            }
        } catch (Exception ex) {
            LOG.error("Fehler beim auslesen der Kommandozeilen Parameter", ex);
            System.exit(1);
        }
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    final PlasticXPLookAndFeel lf = new PlasticXPLookAndFeel();
                    javax.swing.UIManager.setLookAndFeel(lf);
                } catch (Exception ex) {
                    LOG.error("Fehler beim setzen des Look & Feels", ex);
                }
                try {
                    SPLASH = StaticStartupTools.showGhostFrame(FILEPATH_SCREEN, "FIS Gewässer [Startup]");
                    SPLASH.setLocationRelativeTo(null);
                } catch (Exception e) {
                    LOG.warn("Problem beim Darstellen des Pre-Loading-Frame", e);
                }
                try {
//                        handleLogin();
                    AppBroker.getInstance().setLoggedIn(true);
                    if (LOG.isDebugEnabled()) {
                        LOG.debug("Login erfolgreich");
                    }
                    final WatergisApp app = new WatergisApp();
                    app.setVisible(true);
                    if (SPLASH != null) {
                        SPLASH.dispose();
                    }
                    SPLASH = null;
                } catch (Exception ex) {
                    LOG.error("Fehler beim Loginframe", ex);
                    System.exit(0);
                }
            }
        });
    }

    @Override
    public Element getConfiguration() {
        final Element ret = new Element("cismapPluginUIPreferences");
        final Element window = new Element("window");
        final int windowHeight = this.getHeight();
        final int windowWidth = this.getWidth();
        final int windowX = (int) this.getLocation().getX();
        final int windowY = (int) this.getLocation().getY();
        final boolean windowMaximised = (this.getExtendedState() == MAXIMIZED_BOTH);
        if (LOG.isDebugEnabled()) {
            LOG.debug("Windowsize: width " + windowWidth + " height " + windowHeight);
        }
        window.setAttribute("height", "" + windowHeight);
        window.setAttribute("width", "" + windowWidth);
        window.setAttribute("x", "" + windowX);
        window.setAttribute("y", "" + windowY);
        window.setAttribute("max", "" + windowMaximised);
        ret.addContent(window);
        return ret;
    }

    @Override
    public void masterConfigure(final Element parent) {
//        try {
//            // ToDo if it fails all fail better place in the single try catch
//            final Element urls = parent.getChild("urls");
//            final Element albConfiguration = parent.getChild("albConfiguration");
//            try {
//                if (LOG.isDebugEnabled()) {
//                    LOG.debug("OnlineHilfeUrl: " + urls.getChildText("onlineHelp"));
//                }
//                onlineHelpURL = urls.getChildText("onlineHelp");
//            } catch (Exception ex) {
//                LOG.warn("Fehler beim lesen der OnlineHilfe URL", ex);
//            }
//            try {
//                albURL = albConfiguration.getChildText("albURL");
//                if (albURL != null) {
//                    albURL = albURL.trim();
//                }
//                if (LOG.isDebugEnabled()) {
//                    LOG.debug("ALBURL: " + albURL.trim());
//                }
//            } catch (Exception ex) {
//                LOG.warn("Fehler beim lesen der ALB Konfiguration", ex);
//            }
//            try {
//                if (LOG.isDebugEnabled()) {
//                    LOG.debug("News Url: " + urls.getChildText("onlineHelp"));
//                }
//                newsURL = urls.getChildText("news");
//            } catch (Exception ex) {
//                LOG.warn("Fehler beim lesen der News Url", ex);
//            }
//
//        } catch (Exception ex) {
//            LOG.error("Fehler beim konfigurieren der Watergis Applikation: ", ex);
//        }
    }

    @Override
    public void dispose() {
        try {
            StaticStartupTools.saveScreenshotOfFrame(this, FILEPATH_SCREEN);
        } catch (Exception ex) {
            LOG.fatal("Fehler beim Capturen des App-Inhaltes", ex);
        }

        setVisible(false);
        LOG.info("Dispose(): Watergis wird heruntergefahren");

//        this.saveAppData(FILEPATH_DEFAULT_APP_DATA);

        configManager.writeConfiguration();
        saveLayout(FILEPATH_DEFAULT_LAYOUT);

        super.dispose();
        System.exit(0);
    }

    /**
     * DOCUMENT ME!
     *
     * @param file DOCUMENT ME!
     */
    public void saveLayout(final String file) {
        // AppBroker.getInstance().setTitleBarComponentpainter(AppBroker.DEFAULT_MODE_COLOR);
        if (LOG.isDebugEnabled()) {
            LOG.debug("Saving Layout.. to " + file);
        }
        final File layoutFile = new File(file);
        try {
            if (!layoutFile.exists()) {
                if (LOG.isDebugEnabled()) {
                    LOG.debug("Saving Layout.. File '" + file + "' does not exit");
                }
                layoutFile.createNewFile();
            } else {
                if (LOG.isDebugEnabled()) {
                    LOG.debug("Saving Layout.. File '" + file + "' does exit");
                }
            }
            final FileOutputStream layoutOutput = new FileOutputStream(layoutFile);
            final ObjectOutputStream out = new ObjectOutputStream(layoutOutput);
            rootWindow.write(out);
            out.flush();
            out.close();
            if (LOG.isDebugEnabled()) {
                LOG.debug("Saving Layout.. to " + file + " successfull");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(
                    this,
                    "W\u00E4hrend dem Speichern des Layouts ist ein Fehler aufgetreten.",
                    "Fehler",
                    JOptionPane.INFORMATION_MESSAGE);
            LOG.error("A failure occured during writing the layout file " + file, ex);
        }
    }

    @Override
    public void configure(final Element parent) {
        final Element prefs = parent.getChild("cismapPluginUIPreferences");
        if (prefs == null) {
            LOG.warn("there is no local configuration 'cismapPluginUIPreferences'");
        } else {
            try {
                if (LOG.isDebugEnabled()) {
                    LOG.debug("setting windowsize of application");
                }
                final Element window = prefs.getChild("window");
                if (window == null) {
                    LOG.warn("there is no 'window' configuration in 'cismapPluginUIPreferences'");
                } else {
                    final int windowHeight = window.getAttribute("height").getIntValue();
                    final int windowWidth = window.getAttribute("width").getIntValue();
                    final int windowX = window.getAttribute("x").getIntValue();
                    final int windowY = window.getAttribute("y").getIntValue();
                    final boolean windowMaximised = window.getAttribute("max").getBooleanValue();
                    windowSize = new Dimension(windowWidth, windowHeight);
                    windowLocation = new Point(windowX, windowY);
                    if (LOG.isDebugEnabled()) {
                        LOG.debug("windowSize: width " + windowWidth + " heigth " + windowHeight);
                    }
                    // TODO why is this not working
                    // mapComponent.formComponentResized(null);
                    if (windowMaximised) {
                        this.setExtendedState(MAXIMIZED_BOTH);
                    } else {
                    }
                    if (LOG.isDebugEnabled()) {
                        LOG.debug("setting of window successful");
                    }
                }
            } catch (Exception t) {
                // TODO defaults
                LOG.error("Error while setting windowsize", t);
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JMenu menBookmark;
    private javax.swing.JMenu menFile;
    private javax.swing.JMenu menHelp;
    private javax.swing.JMenu menSelection;
    private javax.swing.JMenuItem mniClose;
    private javax.swing.JMenuItem mniCreateBookmark;
    private javax.swing.JMenuItem mniCreateGeoLink;
    private javax.swing.JMenuItem mniExportMap;
    private javax.swing.JMenuItem mniFileOptions;
    private javax.swing.JMenuItem mniHelp;
    private javax.swing.JMenuItem mniInfo;
    private javax.swing.JMenuItem mniManageBookmarks;
    private javax.swing.JMenuItem mniOpenProject;
    private javax.swing.JMenuItem mniPrint;
    private javax.swing.JMenuItem mniRemoveSelection;
    private javax.swing.JMenuItem mniSaveProject;
    private javax.swing.JMenuItem mniSelectAttribute;
    private javax.swing.JMenuItem mniSelectForm;
    private javax.swing.JMenuItem mniSelectLocation;
    private javax.swing.JMenuItem mniSelectionOptions;
    private javax.swing.JMenuItem mniWindow;
    private javax.swing.JMenuItem mniZoomSelectedObjects;
    // End of variables declaration//GEN-END:variables
    @Override
    public void windowOpened(WindowEvent e) {
    }

    @Override
    public void windowClosing(WindowEvent e) {
        if (LOG.isDebugEnabled()) {
            LOG.debug("windowClosing():");
        }
        cleanUp();
        dispose();
    }

    @Override
    public void windowClosed(WindowEvent e) {
    }

    @Override
    public void windowIconified(WindowEvent e) {
    }

    @Override
    public void windowDeiconified(WindowEvent e) {
    }

    @Override
    public void windowActivated(WindowEvent e) {
    }

    @Override
    public void windowDeactivated(WindowEvent e) {
    }

    private void cleanUp() {
    }

    private void setWindowSize() {
        if ((windowSize != null) && (windowLocation != null)) {
            this.setSize(windowSize);
            this.setLocation(windowLocation);
        } else {
            this.pack();
        }
    }
}
